name: Build API Docker Image

on:
  release:
    branches: [main]
    types: [published]
    paths:
      - api/user/**
      - .github/workflows/build-api.yaml

env:
  REGISTRY: ghcr.io/dnjooiopa

jobs:
  build_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          context: ./api
          file: ./api/Dockerfile
          tags: ${{ env.REGISTRY }}/lnf-api:latest,${{ env.REGISTRY }}/lnf-api:${{ github.event.release.tag_name }}
